#ifndef _SELECT_PROGRAM_H
#define _SELECT_PROGRAM_H

#define HELLO_WORLD 0
#define TEST_TEMP 1
#define MOTION_DETECT 2
#define TEMP_TRANSMIT 3
#define MOTION_TRANSMIT 4

#define PROGRAM MOTION_DETECT
#endif
